### ISSUE TITLE
Cannot connect to the stream with demo accounts

### ISSUE THREAD

**Issue by SoftTrading** [IG-Group/ig-webapi-dotnet-sample#18]
Hello,
Since a few days, this application doesn't work anymore to connect to the stream with the IG demo accounts.
I think the problem comes from the IG lightstreamer servers, but I don't know where the problem is.
Do you have any idea?
Should I update the lightstreamer client?
Thanks

**Comment by teebeast** [comment]
I forked this project and fixed some things. See Issue #12. Maybe it helps you. I used it with my demo account from IG and it works. I updated [Lightstreamer](https://github.com/Lightstreamer/Lightstreamer-lib-client-dotnet) to the latest version, but it does not work with my IG account, only to version 5.0.5.

**Comment by SoftTrading** [comment]
Thanks for your help.
But taking into account your remarks the application still can't connect to the stream and the error message on 'Connect' is the following:
"Could NOT connect to Lightstreamer.Endpoint=https://demo-apd.marketdatasystems.com"

**Comment by teebeast** [comment]
I fixed it in my fork. Give it a try. I updated the nuget package from Lightstreamer.DotNet.Client to Lightstreamer.DotNetStandard.Client.

**Comment by SoftTrading** [comment]
I took Lightstreamer.DotNetStandard.Client in version 5.0.5 and it still doesn't work.
The error message is "the transport stream has been disconnected.

**Comment by teebeast** [comment]
I retested my [Fork](https://github.com/teebeast/ig-webapi-dotnet-sample) with my demo account and it's running fine. It is ready to test, when you change the account information in `app.config`. 

I have not tested all aspects of this application, but basically it should work.

**Comment by SoftTrading** [comment]
@(teebeast) :

Thanks for your help.
I tried with your Fork but here is the message I get: 
![Capture20220124](https://user-images.githubusercontent.com/97411461/150780096-ba95148a-dee1-4a6c-af02-ba645b42b5d2.JPG)

**Comment by teebeast** [comment]
Hm, I have no problems. It shows you a list of accounts? You have to set the key `account` in `app.config`, which is originally not required. The list of accounts shows it to you as `account id`. It must be a CFD account type.

Hope this helps.

![image](https://user-images.githubusercontent.com/20777572/150784665-210435ec-bab3-464a-a10a-3503e9705a77.png)

**Comment by SoftTrading** [comment]
And now it works for the demo account but not for the live account.
Really impossible to understand at my level

**Comment by teebeast** [comment]
When you use your live account, your environment should also be "live" and not "demo".

**Comment by ireay** [comment]
@SoftTrading  did you get this working in the end in both environments? Note that the sample code keeps track of the context roots of each environment and then appends the rest of the URL onto the environment's context root.

**Comment by Ketu748** [comment]
Is there any reason why context = IgRestApiClient.GetConversationContext(); isn't holding the values of cst and xSecurityToken?

**Comment by thompsont1962** [comment]
@teebeast
I cannot get the "fork" solution to connect  lightstreamer and I cannot see how it could.
To connect to lightstreamer the xSecurityToken is needed, but this is not returned in a V3 PUT session authentication. Hence Ketu748's comment here

As the IG docs say
"The streaming API currently does not accept OAuth tokens so users holding OAuth bearer tokens should call GET /session?fetchSessionTokens=true to obtain CST and X-SECURITY-TOKEN tokens."
regards Tom

**Comment by teebeast** [comment]
> @teebeast I cannot get the "fork" solution to connect lightstreamer and I cannot see how it could. To connect to lightstreamer the xSecurityToken is needed, but this is not returned in a V3 PUT session authentication. Hence Ketu748's comment here

@thompsont1962, I fixed it. The GET request /session?fetchSessionTokens=true was missing. In the end a simple line of code. In my own implementation everything is working fine.
